const animationClipMap: Record<string, string> = {
  turn_dancing: "F_Dances_001",
  cartwheel: "F_Dances_004",
  turn_hand_waving_dancing: "F_Dances_005",
  sexy_dancing: "F_Dances_006",
  backflip: "F_Dances_007",

  psy_dance: "M_Dances_001",
  tobey_spiderman_dance: "M_Dances_002",
  party_dance: "M_Dances_003",
  cheese_dance: "M_Dances_004",
  fortnite_dance: "M_Dances_005",
  round_and_round_dance: "M_Dances_006",
  wave_dance: "M_Dances_007",
  row_row_boat_dance: "M_Dances_008",
  fornite_dance: "M_Dances_009",
  breakdance: "M_Dances_011",

  wave_hello: "M_Standing_Expressions_001",
  hand_pointing_at_you: "M_Standing_Expressions_002",
  nod_head_approve: "M_Standing_Expressions_004",
  dont_know_dont_care: "M_Standing_Expressions_005",
  sleepy_stretch: "M_Standing_Expressions_006",
  sneeze: "M_Standing_Expressions_007",
  hand_pointing_toyou_comehere: "M_Standing_Expressions_008",
  come_here_look_down: "M_Standing_Expressions_009",
  come_here_look_at_you: "M_Standing_Expressions_010",
  stop_it_no_way: "M_Standing_Expressions_011",
  good_good: "M_Standing_Expressions_012",
  wave_hello_energetic: "M_Standing_Expressions_013",
  checkout_left_and_right: "M_Standing_Expressions_014",
  stopp: "M_Standing_Expressions_015",
  you_are_baddd: "M_Standing_Expressions_016",
  booooo_not_good: "M_Standing_Expressions_017",
  you_re_deadd: "M_Standing_Expressions_018",

  // Talking
  chatting_polite_hands: "F_Talking_Variations_001",
  chatting_hands_on_down: "F_Talking_Variations_002",
  chatting_describing_big: "F_Talking_Variations_003",
  chatting_holdchest: "F_Talking_Variations_004",
  chatting_handsup_little: "F_Talking_Variations_005",
  chatting_armup_little: "F_Talking_Variations_006",
  chatting_conversation: "M_Talking_Variations_001",
  chatting_casual: "M_Talking_Variations_002",
  chatting_imsure_gesture: "M_Talking_Variations_003",
  chatting_nono_or_done: "M_Talking_Variations_004",
  chatting_more_movement: "M_Talking_Variations_005",
  chatting_dontknow_dontcare: "M_Talking_Variations_006",
  chatting_dontcare_lessmovement: "M_Talking_Variations_007",
  chatting_head_shake_no: "M_Talking_Variations_008",
  chatting_you_know_right: "M_Talking_Variations_009",
  chatting_its_cool_right: "M_Talking_Variations_010",
};

export default animationClipMap;