const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.17,
    noseSneerRight: 0.14,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41,
  },
   smiles: {
    browDownLeft: 1,
    browDownRight: 1,
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.17,
    noseSneerRight: 1,
    mouthPressLeft: 1,
    mouthPressRight: 1,

    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78,
    jawForward: 1,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78,
    browInnerUp: 0.45,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  sinister: {
    browInnerUp: 0.1,
    eyeSquintLeft: 0.3,
    eyeSquintRight: 0.3,
    noseSneerLeft: 0.1,
    noseSneerRight: 0.1,
    jawLeft: 0.4,
    mouthPucker: 0.3,
    mouthLeft: 0.5,
    cheekPuff: 0.2,
    mouthDimpleLeft: 0.15,
    mouthRollLower: 0.2,
    mouthSmileLeft: 0.5,
    mouthSmileRight: 0.1, // asymmetry for unsettling look
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.35,
    mouthFunnel: 0.3,
    browInnerUp: 1,
  },
  teasing: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.57,
    noseSneerRight: 0.51,
    jawOpen: 0.96,
    mouthDimpleLeft: 0.5,
    mouthDimpleRight: 0.5,
    mouthStretchLeft: 0.26,
    mouthStretchRight: 0.23,
    mouthSmileLeft: 0.3,
    mouthSmileRight: 0.2,
    tongueOut: 0.1,
  },
  confused: {
    browInnerUp: 0.4,
    browDownLeft: 0.3,
    browDownRight: 0.1,
    eyeLookUpLeft: 0.4,
    eyeLookUpRight: 0.2,
    mouthFrownLeft: 0.3,
    mouthFrownRight: 0.2,
    mouthShrugLower: 0.4,
  },
  flirty: {
    browInnerUp: 0.3,
    eyeLookUpLeft: 0.3,
    eyeSquintLeft: 0.4,
    mouthSmileLeft: 0.5,
    mouthSmileRight: 0.3,
    mouthDimpleLeft: 0.3,
    cheekPuff: 0.2,
  },
  thinking: {
    browInnerUp: 0.2,
    eyeLookUpLeft: 0.4,
    eyeLookUpRight: 0.4,
    mouthPressLeft: 0.5,
    jawForward: 0.2,
  },
  sleepy: {
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    eyeSquintLeft: 0.8,
    eyeSquintRight: 0.8,
    browInnerUp: 0.1,
    mouthShrugLower: 0.3,
  },
  kissing: {
    mouthPucker: 1, 
    mouthFunnel: 0.4, 
    jawForward: 0.3, 
    eyeSquintLeft: 0.4, 
    eyeSquintRight: 0.4,
    browInnerUp: 0.2, 
    mouthClose: 0.3,
  },
  smileWithTeeth: {
    mouthSmileLeft: 1,
    mouthSmileRight: 1,
    cheekSquintLeft: 0.3,
    cheekSquintRight: 0.3,
    eyeSquintLeft: 0.2,
    eyeSquintRight: 0.2,
    jawOpen: 0.1,
    mouthOpen: 0.3, // optional if using RPM-style blendshapes
    browInnerUp: 0.2,
    mouthUpperUpLeft: 0.4,
    mouthUpperUpRight: 0.4,
  },
  scared: {
    browInnerUp: 0.4, // worried brows
    browDownLeft: 0.7,
    browDownRight: 0.7,
    eyeWideLeft: 0.8, // panic/fear eyes
    eyeWideRight: 0.8,
    mouthFrownLeft: 1, // sad + scared mouth
    mouthFrownRight: 1,
    mouthShrugLower: 0.5, // trembling bottom lip
    jawOpen: 0.2, // just a bit open
    cheekSquintLeft: 0.2,
    cheekSquintRight: 0.2,
  },
};

export default facialExpressions;
